### ISSUE TITLE
Verbose logging for TUI

### ISSUE THREAD

**Issue by orhun** [orhun/systeroid#11]
**Is your feature request related to a problem? Please describe.**
Printing to stdout is not possible while running TUI since the output is locked by the terminal backend (`termion`). This causes [verbose logging](https://github.com/orhun/systeroid/blob/17c1ea61f958ad39fcd3d40b312243d6e7a84996/systeroid-core/src/sysctl/controller.rs#L39) to be suppressed.

**Describe the solution you'd like**
Add a new command-line flag named `--verbose` and somehow enable verbose logging while running the TUI.

**Describe alternatives you've considered**
\-

**Additional context**
This will be useful when some of the parameters cannot be retrieved due to insufficient permissions and error logs are printed. Right now there is no way of telling when the parameter list is fetched without errors when the TUI is launched.

**Comment by koutheir** [comment]
Logging to the terminal when a TUI is rendered might cause rendering issues. Have you considered the following alternatives:
- Logging to a log file.
- Logging to the `syslog`.
- Tearing down the TUI right before printing to `stderr`.

**Comment by orhun** [comment]
Thank you for the ideas @koutheir!

Another alternative would be using [tui-logger](https://github.com/gin66/tui-logger).

**Comment by koutheir** [comment]
Logging inside TUI would make the logs unavailable for further analysis at a later date, which is a very common use case for logs.

**Comment by orhun** [comment]
What do you suggest here? @koutheir

**Comment by koutheir** [comment]
I suggest saving the log entries to a log file that can be analyzed after the fact.

**Comment by orhun** [comment]
[`tui-logger`](https://github.com/gin66/tui-logger) supports saving the logs to a file and also provides a smart widget for analyzing them. I implemented a draft at #83
