### ISSUE TITLE
Support saving changed values

### ISSUE THREAD

**Issue by kevinclevenger** [orhun/systeroid#13]
**Describe the solution you'd like**
Support saving changed values to a specified file, i.e. 99-local.conf (possibly specified in a config file in RFE #12) 

**Describe alternatives you've considered**
Could also dump changed values to terminal in a format suitable for copy/paste

**Comment by orhun** [comment]
This is now implemented in [1fda373](https://github.com/orhun/systeroid/commit/1fda3736026eecbe7cb7d47b6d2ffd75534df97b)

You can press <kbd>s</kbd> to set a parameter value and save it to a file specified by `--save-path` (or configuration file).

![demo](https://raw.githubusercontent.com/orhun/systeroid/main/assets/systeroid-tui-save-value.gif)

See https://github.com/orhun/systeroid#saving-values

I will be pushing a release soon.

**Comment by ngirard** [comment]
Excellent, thanks !
