### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by omnivagant** [orhun/systeroid#153]
It would be nice to be able to set transparent background or, if already possible, documented how to.

Or, maybe the background shouldn't be overridden with the default black, if that would be a way?

**Comment by orhun** [comment]
Hey, thanks for creating this issue! 🐻 

You can do:

```sh
systeroid-tui --bg-color reset
```

Documented in 48e5ad6cc62fe498a73f8a7ece9580d0b68aeee2
